import { ChatMessage, ScoringResult, scoreInterview } from './scorer';
import { SYSTEM_PROMPT, renderUserPrompt } from './prompts';
import { config } from '../config';
import logger from '../utils/logger';

export interface EnhancedScoringResult extends ScoringResult {
  reasoning: {
    technical: string;
    communication: string;
    relevance: string;
  };
  citations: Array<{
    quote: string;
    stage: string;
    dimension: string;
  }>;
  detailed_feedback: string;
  scoring_method: 'LLM' | 'RULE_BASED';
}

export interface BaseScorer {
  score(chatHistory: ChatMessage[], requirementsText?: string): Promise<EnhancedScoringResult>;
}

/**
 * Validates that the citations generated by the LLM exist as substrings
 * within the candidate's actual responses in the chat history.
 */
export function validateCitations(
  citations: any[],
  chatHistory: ChatMessage[]
): Array<{ quote: string; stage: string; dimension: string }> {
  if (!Array.isArray(citations)) return [];

  const candidateMessages = chatHistory
    .filter((m) => m.role === 'CANDIDATE')
    .map((m) => m.content.toLowerCase().replace(/\s+/g, ' ').trim());

  return citations
    .filter((cit) => {
      if (!cit || typeof cit !== 'object') return false;
      const quote = (cit.quote || '').toLowerCase().replace(/\s+/g, ' ').trim();
      return quote.length > 0 && candidateMessages.some((msg) => msg.includes(quote));
    })
    .map((cit) => ({
      quote: cit.quote.trim(),
      stage: cit.stage || 'TECHNICAL_QUESTIONS',
      dimension: cit.dimension || 'technical',
    }));
}

/**
 * Smart Mock Scorer that simulates LLM-based output.
 * It runs the rule-based scorer internally, and builds realistic reasoning and actual citations.
 */
export class MockLlmScorer implements BaseScorer {
  async score(chatHistory: ChatMessage[], requirementsText?: string): Promise<EnhancedScoringResult> {
    logger.info({ event: 'scoring.llm.mock_start', message: 'Using MockLlmScorer' });

    // Step 1: Run standard rule-based scorer to get realistic base metrics
    const baseResult = scoreInterview(chatHistory, requirementsText);

    // Step 2: Extract real quotes from candidate messages to construct valid citations
    const citations: Array<{ quote: string; stage: string; dimension: string }> = [];

    const candidateMsgs = chatHistory.filter((m) => m.role === 'CANDIDATE');

    const techMsg = candidateMsgs.find((m) => m.stage === 'TECHNICAL_QUESTIONS') || candidateMsgs[0];
    if (techMsg) {
      citations.push({
        quote: techMsg.content.length > 100 ? techMsg.content.slice(0, 97) + '...' : techMsg.content,
        stage: techMsg.stage,
        dimension: 'technical',
      });
    }

    const commMsg = candidateMsgs.find((m) => m.content.length > 40) || candidateMsgs[0];
    if (commMsg && commMsg !== techMsg) {
      citations.push({
        quote: commMsg.content.length > 100 ? commMsg.content.slice(0, 97) + '...' : commMsg.content,
        stage: commMsg.stage,
        dimension: 'communication',
      });
    }

    const relMsg = candidateMsgs.find((m) => m.stage === 'EXPERIENCE_REVIEW') || candidateMsgs[1] || candidateMsgs[0];
    if (relMsg && relMsg !== techMsg && relMsg !== commMsg) {
      citations.push({
        quote: relMsg.content.length > 100 ? relMsg.content.slice(0, 97) + '...' : relMsg.content,
        stage: relMsg.stage,
        dimension: 'relevance',
      });
    }

    // Step 3: Fabricate realistic reasoning texts based on score levels
    const reasoning = {
      technical: baseResult.scores.technical >= 75
        ? `Candidate demonstrated solid technical knowledge, correctly matching multiple key stacks. Specifically, they elaborated: "${citations[0]?.quote || 'relevant topics'}".`
        : `Candidate showed limited technical knowledge. Gaps were observed in their answers compared to the job requirements.`,
      communication: baseResult.scores.communication >= 75
        ? `Clear and structured communication. Responses were detailed, descriptive, and maintained a highly professional tone.`
        : `Responses were somewhat short and brief, lacking detailed explanations.`,
      relevance: baseResult.scores.relevance >= 75
        ? `Excellent role alignment. Their experience matches the requirements closely.`
        : `Some answers departed from the interviewer's queries or lacked focus.`,
    };

    const detailedFeedback = `The candidate demonstrated an overall score of ${baseResult.scores.overall}/100. ` +
      `Strengths include: ${baseResult.strengths.join(', ')}. ` +
      `For next steps, recommend digging deeper into: ${baseResult.weaknesses.join(', ')}.`;

    return {
      ...baseResult,
      reasoning,
      citations,
      detailed_feedback: detailedFeedback,
      scoring_method: 'LLM',
    };
  }
}

/**
 * Real LLM Scorer calling OpenAI or Gemini REST APIs.
 */
export class LlmScorer implements BaseScorer {
  private mockScorer = new MockLlmScorer();

  async score(chatHistory: ChatMessage[], requirementsText?: string): Promise<EnhancedScoringResult> {
    const provider = config.llmProvider;
    const apiKey = config.llmApiKey;

    if (!apiKey) {
      logger.info({ event: 'scoring.llm.missing_key', message: 'No API key provided. Falling back to MockLlmScorer.' });
      return this.mockScorer.score(chatHistory, requirementsText);
    }

    try {
      const userPrompt = renderUserPrompt(chatHistory, requirementsText || '');
      let jsonText = '';

      if (provider === 'gemini') {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=${apiKey}`;
        logger.info({ event: 'scoring.llm.request_gemini', provider, model: 'gemini-3.5-flash' });

        const response = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [
              {
                role: 'user',
                parts: [{ text: `${SYSTEM_PROMPT}\n\n${userPrompt}` }],
              },
            ],
            generationConfig: {
              responseMimeType: 'application/json',
              temperature: 0.2,
            },
          }),
        });

        if (!response.ok) {
          throw new Error(`Gemini API returned status ${response.status}: ${await response.text()}`);
        }

        const data = (await response.json()) as any;
        jsonText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      } else {
        // Default: openai
        const url = 'https://api.openai.com/v1/chat/completions';
        logger.info({ event: 'scoring.llm.request_openai', provider, model: 'gpt-4o-mini' });

        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: 'gpt-4o-mini',
            messages: [
              { role: 'system', content: SYSTEM_PROMPT },
              { role: 'user', content: userPrompt },
            ],
            response_format: { type: 'json_object' },
            temperature: 0.2,
          }),
        });

        if (!response.ok) {
          throw new Error(`OpenAI API returned status ${response.status}: ${await response.text()}`);
        }

        const data = (await response.json()) as any;
        jsonText = data?.choices?.[0]?.message?.content;
      }

      if (!jsonText) {
        throw new Error('LLM response returned empty content');
      }

      const result = JSON.parse(jsonText);

      // Validate schema format
      if (!result.scores || typeof result.scores !== 'object') {
        throw new Error('Missing scores object in LLM response');
      }

      const technical = Number(result.scores.technical || 50);
      const communication = Number(result.scores.communication || 50);
      const relevance = Number(result.scores.relevance || 50);
      const overall = Number(result.scores.overall || Math.round(technical * 0.4 + communication * 0.3 + relevance * 0.3));

      // Validate citations
      const validatedCitations = validateCitations(result.citations || [], chatHistory);

      return {
        scores: { technical, communication, relevance, overall },
        summary: result.summary || 'AI Assessment generated successfully.',
        strengths: Array.isArray(result.strengths) ? result.strengths : [],
        weaknesses: Array.isArray(result.weaknesses) ? result.weaknesses : [],
        recommendation: result.recommendation || (overall >= 80 ? 'ADVANCE_TO_NEXT_ROUND' : overall >= 65 ? 'CONSIDER' : 'REJECT'),
        reasoning: {
          technical: result.reasoning?.technical || 'No technical reasoning provided.',
          communication: result.reasoning?.communication || 'No communication reasoning provided.',
          relevance: result.reasoning?.relevance || 'No relevance reasoning provided.',
        },
        citations: validatedCitations,
        detailed_feedback: result.detailed_feedback || 'No detailed feedback provided.',
        scoring_method: 'LLM',
      };
    } catch (err: any) {
      logger.error({
        event: 'scoring.llm.failed',
        message: 'LLM scoring failed. Falling back to MockLlmScorer.',
        error: err.message,
      });
      // Falling back to MockLlmScorer is much safer for a soft failure, as it keeps returning the correct schema!
      return this.mockScorer.score(chatHistory, requirementsText);
    }
  }
}
